spring:
  profiles:
    active: dev

  application:
    name: sb01-monew-team6
    version: 1.0.0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

notification:
  batch:
    size: 10000

storage:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY_ID}
    secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket: ${AWS_BUCKET}

log:
  dir: .logs