spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#  data:
#    mongodb:
#      database: ${MONGO_DB_DATABASE} # user_api
#      host: ${MONGO_DB_HOST} # localhost
#      port: ${MONGO_DB_PORT} # 27017
#      auto-index-creation: true

decorator:
  datasource:
    enabled: false