spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev

  jpa:
    properties:
      hibernate:
        format_sql: true

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url:
#    username:
#    password:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

naver:
  api:
    url: https://openapi.naver.com/v1/search/news.json  # 네이버 뉴스 API
    client-id: ${naver.api.client-id}                      # 발급받은 Client ID
    client-secret: ${naver.api.client-secret}                   # 발급받은 Client Secret