spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}

#logging:
  #level:
    #org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace