spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  health:
    mongo:
      enabled: false

rss:
  feeds:
    - name: HANKYUNG
      url: https://www.hankyung.com/feed/all-news
    - name: YEONHAP
      url: https://www.yna.co.kr/rss/news.xml
    - name: YEONHAP_POLITICS
      url: https://www.yna.co.kr/rss/politics.xml
    - name: JTBC
      url: https://news-ex.jtbc.co.kr/v1/get/rss/issue
#naver:
#  api:
#    url: ${naver.api.url}  # 네이버 뉴스 API
#    client-id: ${naver.api.client-id}                      # 발급받은 Client ID
#    client-secret: ${naver.api.client-secret}                   # 발급받은 Client Secret
