spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    mongodb:
      database: ${MONGO_DB_DATABASE} # user_api
      host: ${MONGO_DB_HOST} # localhost
      port: ${MONGO_DB_PORT} # 27017
      auto-index-creation: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  health:
    mongo:
      enabled: false

naver:
  api:
    url: https://openapi.naver.com/v1/search/news.json  # 네이버 뉴스 API
    client-id: ${naver.api.client-id}                      # 발급받은 Client ID
    client-secret: ${naver.api.client-secret}                   # 발급받은 Client Secret
