name: CI - Build and Test

# 워크플로우 트리거 조건 정의
on:
  push:
    branches: [ main ]     # main 브랜치에 push될 때 실행
  pull_request:             # PR이 열리거나 업데이트될 때 실행 (브랜치 제한 없음)

# 실행할 작업 정의
jobs:
  build:                    # build라는 이름의 Job 정의
    runs-on: ubuntu-latest # Ubuntu 최신 환경에서 실행

    steps:                 # Job 내 단계 정의
      # 1단계: 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2단계: JDK 17 설치 (Temurin 배포판 사용)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # 사용할 Java 버전
          distribution: 'temurin'    # Temurin (Adoptium) 배포판 선택

      # 3단계: gradlew 파일에 실행 권한 부여 (Linux에서는 필수)
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      # 4단계: Gradle로 전체 빌드 및 테스트 실행
      - name: Build and Test with Gradle
        run: ./gradlew clean build   # clean: 이전 빌드 삭제, build: 컴파일 + 테스트 수행
